[[legate]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47ce90d4ebc3841906c144857f1dec1f03f9e594"
lazy = true
libc = "glibc"
os = "linux"

    [[legate.download]]
    sha256 = "8869c3179d51c85d7861eaffee7358f3cbcde6f788dc94af9aefbbc36f9ca496"
    url = "https://github.com/JuliaBinaryWrappers/legate_jll.jl/releases/download/legate-v25.10.2+0/legate.v25.10.2.x86_64-linux-gnu-cxx11-cuda+none.tar.gz"
[[legate]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7539f7d5d7cd79172361eca36b75096d3b67dbd2"
lazy = true
libc = "glibc"
os = "linux"

    [[legate.download]]
    sha256 = "41b3ff06493afabf3fde68fd1c2f57fe802b8df385971343964fa97d2a946dae"
    url = "https://github.com/JuliaBinaryWrappers/legate_jll.jl/releases/download/legate-v25.10.2+0/legate.v25.10.2.x86_64-linux-gnu-cxx11-cuda+13.0.tar.gz"
