[[legate]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "19618e432bb12a0854cb4a81d78bcb5858569b2b"
lazy = true
libc = "glibc"
os = "linux"

    [[legate.download]]
    sha256 = "e016e87300117c5d5116711dca97db1fee2b95bd67f0f16b4075289d383c0f0d"
    url = "https://github.com/JuliaBinaryWrappers/legate_jll.jl/releases/download/legate-v25.10.0+1/legate.v25.10.0.x86_64-linux-gnu-cxx11-cuda+none.tar.gz"
[[legate]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0df031e4aae4e99b685b699155fdd84350399e63"
lazy = true
libc = "glibc"
os = "linux"

    [[legate.download]]
    sha256 = "4e4675a4f9c6a6015f7b8d0de6f006b3093b66d7387912e635f5bbc95a737c48"
    url = "https://github.com/JuliaBinaryWrappers/legate_jll.jl/releases/download/legate-v25.10.0+1/legate.v25.10.0.x86_64-linux-gnu-cxx11-cuda+13.0.tar.gz"
